#!/bin/sh
cd web-admin/
go build -o ./tmp/web_main 
./tmp/web_main &
WEB_PID=$!
cd ..
cd api/
go build -o ./tmp/api_main
./tmp/api_main &
API_PID=$!
cd ..
# echo  $!
# echo $MAIN_PID
while inotifywait -e modify web-admin/* e-modify api/* ; do
    kill $WEB_PID
    kill $API_PID

    cd web-admin/
    go build -o ./tmp/web_main 
    ./tmp/web_main &
    WEB_PID=$!
    cd ..
    cd api/
    go build -o ./tmp/api_main
    ./tmp/api_main &
    API_PID=$!
    cd ..

#     cd app/
#     go build -o ../tmp/main
#     cd ..
#     ./tmp/main &
#     MAIN_PID=$!
#     # echo "reload" > "writable/stream.txt"
done
